/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const demosIndexLazyImport = createFileRoute('/(demos)/')()
const demosRealtimeLazyImport = createFileRoute('/(demos)/realtime')()
const demosCrudLazyImport = createFileRoute('/(demos)/crud')()

// Create/Update Routes

const demosIndexLazyRoute = demosIndexLazyImport
  .update({
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(demos)/index.lazy').then((d) => d.Route))

const demosRealtimeLazyRoute = demosRealtimeLazyImport
  .update({
    path: '/realtime',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(demos)/realtime.lazy').then((d) => d.Route))

const demosCrudLazyRoute = demosCrudLazyImport
  .update({
    path: '/crud',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(demos)/crud.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(demos)/crud': {
      id: '/crud'
      path: '/crud'
      fullPath: '/crud'
      preLoaderRoute: typeof demosCrudLazyImport
      parentRoute: typeof rootRoute
    }
    '/(demos)/realtime': {
      id: '/realtime'
      path: '/realtime'
      fullPath: '/realtime'
      preLoaderRoute: typeof demosRealtimeLazyImport
      parentRoute: typeof rootRoute
    }
    '/(demos)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof demosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  demosCrudLazyRoute,
  demosRealtimeLazyRoute,
  demosIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/crud",
        "/realtime",
        "/"
      ]
    },
    "/crud": {
      "filePath": "(demos)/crud.lazy.tsx"
    },
    "/realtime": {
      "filePath": "(demos)/realtime.lazy.tsx"
    },
    "/": {
      "filePath": "(demos)/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
